version: '3.9'
services:
  rabbit-queue:
    build:
      context: rabbit-amqp
      dockerfile: Dockerfile
    container_name: rabbit-queue
    image: rabbit-queue-amqp:tag
    ports:
      - 15672:15672
      - 5672:5672
      - 15692:15692